---
services:
  
  mosquitto:
    build:
      context: .
      target: mosquitto_broker
      dockerfile: ./Containerfile
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_log:/mosquitto/log
      - mosquitto_data:/mosquitto/data

  database:
    build:
      context: .
      target: mysql
      dockerfile: ./Containerfile
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: HeL!@SuP3rSEcuRe
      MYSQL_DATABASE: access_system
      MYSQL_USER: mellon
      MYSQL_PASSWORD: Y0USl-l@lL!P@s5
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  migrate:
    image: migrate/migrate:v4.17.0
    environment:
      MYSQL_ROOT_PASSWORD: HeL!@SuP3rSEcuRe
      MYSQL_DATABASE: access_system
      MYSQL_USER: mellon
      MYSQL_PASSWORD: Y0USl-l@lL!P@s5
      DB_CONNECTION_URL: mellon:Y0USl-l@lL!P@s5@tcp(database:3306)/access_system?multiStatements=true
    entrypoint: sleep infinity
    volumes:
      - ./migrations:/migrations

volumes:
  mosquitto_log: {}
  mosquitto_data: {}
  mysql_data: {}
